# Generated by Django 5.0.3 on 2024-04-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_gallery_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
