# Generated by Django 5.0.3 on 2024-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_category_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/static/img/logo1.png', upload_to='article'),
        ),
    ]
